### ISSUE TITLE
Implement sys::getBacktrace() on additional systems

### ISSUE THREAD

**Issue by chvink** [mdaus/coda-oss#149]
sys::getBacktrace() is a function that'll return the current stack of function calls as a string. Take a look at pull request #147 for an example implementation that works when glibc is used.  Unfortunately this is in basically no standard, so we need to add support for different platforms manually. Windows support can be added with [this function to get the stack trace](https://msdn.microsoft.com/en-us/library/windows/desktop/bb204633%28v=vs.85%29.aspx) and [this function to convert the stack trace into text](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681323%28v=vs.85%29.aspx). Unfortunately the latter piece has requirements for static calls to [SymInitialize](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681351%28v=vs.85%29.aspx)/[SymCleanup](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680696%28v=vs.85%29.aspx) so it will take some planning to include this.

**Comment by JDanielSmith** [comment]
Done: [**feature/build-with-cpp17](https://github.com/mdaus/coda-oss/tree/feature/build-with-cpp17) https://github.com/mdaus/coda-oss/blob/feature/build-with-cpp17/modules/c%2B%2B/sys/source/Backtrace.cpp
