### ISSUE TITLE
makewheel flexibility

### ISSUE THREAD

**Issue by asylvest** [mdaus/coda-oss#173]
Currently makewheel finds the appropriate `setup.py` value by looking at `SETUP_PY_DIR`.  This works fine when there's exactly one wheel we want to make in a repo but doesn't work if we have a larger repo that potentially has multiple wheels that it might want to make.

Need to generalize this somehow... it seems like it would be nice to say something like
`waf makewheel --target=wheelName`, have associated that wheel name somehow in a wscript, and then have associated the path to setup.py based on this name.

**Comment by JonathanMeans** [comment]
Can this be closed?

**Comment by asylvest** [comment]
Yep - thanks
