### ISSUE TITLE
Extend datetime to match python datetime string representation

### ISSUE THREAD

**Issue by piyushrpt** [mdaus/coda-oss#180]
Would it be possible to extend sys::dateTime.format() + strptime()  to include a representation to match python datetime?  I couldn't find a format string that would allow one to replicate the inputs in python datetime, if it already exists.

It would be nice if the dateTime include support for fractional seconds (atleast up to microseconds).

Piyush

**Comment by asylvest** [comment]
Piyush,

I think the existing implementation should let you represent most formats (like strptime / strftime, you can send in a format string that is pretty much whatever you want)... can you give us an example of a specific format string you want with expected output that you can't get to work?

I believe you can use `%S` to produce fractional seconds.

**Comment by piyushrpt** [comment]
Parsing works great with %S, but looks like the "format()" functions cannot output fractional seconds? Might need changes to %S parsing in strftime? 

Here is an example: 

```cpp
      sys::UTCDateTime example;
      example.setTime("2015-12-11 10:31:43.555568", "%Y-%m-%d %H:%M  :%S");
      std::cout.precision(17);
      std::cout << "Seconds: " <<  example.getSecond() << "\n";
      std::cout << example.format("%Y-%m-%d %H:%M:%S") << "\n";
      std::cout << example.format("%Y-%m-%d") << "\n";
```

Generates the following output:
```bash
Seconds: 43.555568000000001
2015-12-11 10:31:43
2015-12-11
```

Piyush

**Comment by asylvest** [comment]
Gotcha - yeah I hadn't looked closely enough at the `strftime` manpage but running your example and looking at it again, even though the `tm` struct on line 596 of `DateTime.cpp` has fractional seconds (i.e. it doesn't get lost in the `gmtime_r()` call in `UTCDateTime::getTime()`), `strftime()`'s `%S` modifier just provides it as an integer (it looks like Python's `strftime()` behaves the same way).

This may be obvious but you can get the result you want with...
```
std::cout << example.format("%Y-%m-%d %H:%M:") << example.getSecond() << "\n";
```

Which will generate:
```
2015-12-11 10:31:43.555568000000001
```

Of course it is lame that you need to do it this way but it looks like we're stuck unless we made up a new `%` character and replaced it ourselves before calling `strftime()`.
