### ISSUE TITLE
Name Collision with Mesos

### ISSUE THREAD

**Issue by chvink** [mdaus/coda-oss#214]
In [modules/c++/sys/include/sys/Conf.h](https://github.com/mdaus/coda-oss/blob/master/modules/c%2B%2B/sys/include/sys/Conf.h) on line 174 the definition `#define SYS_TIME sys::TimeStamp().local()` collides with auto-generated code in Mesos-1.1.0. The most immediate fix seems to be just trying to include things in the right order, but something more permanent should be done here in the long run.

@asylvest

**Comment by asylvest** [comment]
grep'ing through the code, the only spot I see we use this is to define the `Ctxt` macro a few lines down.  I'd recommend you put in a PR to remove this `#define` and just put that straight in the `Ctxt` macro
