### ISSUE TITLE
CPUAffinityInitializer not defined for macos

### ISSUE THREAD

**Issue by tclarke** [mdaus/coda-oss#466]
Looks like there's only a Linux and Win32 definition.

**Comment by tclarke** [comment]
https://developer.apple.com/library/archive/releasenotes/Performance/RN-AffinityAPI/#//apple_ref/doc/uid/TP40006635-CH1-DontLinkElementID_2

**Comment by JDanielSmith** [comment]
We have no *MacOS* platform available; please submit a pull-request.
