### ISSUE TITLE
fails to build on windows with bad regex

### ISSUE THREAD

**Issue by kjurka** [mdaus/coda-oss#62]
The build fails on windows because it is trying to perform a regex replacement with a value that has backslashes.

The stacktrace from "python waf configure --prefix=install" results in:

 File "C:\work\sicd\git\coda-oss\build\build.py", line 1610, in handleDefsFile
    code = re.sub(r'#undef %s(\s*\n)' % k, r'#define %s %s\1' % (k,v), code)
  File "C:\Anaconda\lib\re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Anaconda\lib\re.py", line 273, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Anaconda\lib\re.py", line 260, in _compile_repl
    raise error, v # invalid expression
error: missing group name

When adding "print k, v" just before this replacement I see:

PYTHONDIR "C:\work\sicd\git\coda-oss\install\Lib\site-packages"

So the backslashes in the windows path are messing with the intended replacement.  I tried adding a re.esacpe(v), but that ended up escaping a bunch of things that shouldn't be, notably underscores.

**Comment by asylvest** [comment]
Hmm... are you using the latest commit to CODA-OSS (or equivalently, the latest commit to SIX)?  This works fine on Windows for me with what seems to be an equivalent directory structure:

```
(Pdb) print k, v
PYTHONDIR "C:\Users\asylvest\Code\checkout\coda-oss\install\Lib\site-packages"
```

I am using Python 2.7.10 from 64-bit Anaconda 2.3.0, though I believe this logic has been in place for about a year and a half and I haven't seem someone run into an issue like this before using vanilla Python or Anaconda's Python so I'm not sure yet what's different in your case.

If you can't decipher this, can you output the contents of 'code' (maybe save off to a text file) so I can see if it's something else which was set earlier that's causing the problem?

**Comment by kjurka** [comment]
Yes, I am using the latest git commit in coda-oss.  I ran into this trying to build six-library, but thought this was the correct upstream to report this to so I checked out coda-oss directly as well.

Doing a little more testing, the problem is that I have a "git" directory in the path and \g has a special meaning in the replacement part of the sub call.  Try running the following two lines in an interactive python session...

import re
re.sub('x', 'x "C:\work\something"', 'a')
re.sub('x', 'x "C:\work\git\something"', 'a')

**Comment by asylvest** [comment]
Yep, this is the right spot to report it.

Ahh - good sleuthing!  We'll push up a fix here soon.

**Comment by asylvest** [comment]
Hmm, so this is a little bit more of a headache than I was originally thinking.  At first I thought this would be as easy as adding a `v = re.escape(v)` which does fix the immediate problem.  But... this does way more than you want it to and wreaks havoc on the Xerces-generated config.h which will end up containing `#define`s for `wchar\_t` rather than `wchar_t`.  If you've got any suggestions, feel free to provide them.  Otherwise we will continue to gradually take a look into this.

**Comment by asylvest** [comment]
More than likely, `\` is the only thing we've really got to worry about, so we may be able to just get away with replacing `\` with `\\` rather than calling `re.escape()`.

**Comment by kjurka** [comment]
That certainly seems like a reasonable solution.  Once I discovered the problem, I just renamed the directory, but that's not going to be obvious or even potentially an option for others.
